In [1]:
import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

In [37]:
dsa1 = pd.read_csv('grounding_arvor_cmfile_25.csv')
dsa1 = dsa1.sort_values(['WMO']).reset_index()
dsa1

,index,WMO,lon,lat,grnd,uncertainty,tid_flag,SID,gebco,uncertainty2,tid_flag2,gebco2
0,3444,19026211,-28.541053,57.677535,-2461.267351,368.914274,9998,33401,-2524.321396,372.6,9998,-2523.0
1,3503,19026213,-29.900330,57.066900,-2393.815240,269.825786,9998,33401,-2418.856578,314.4,-1,-2417.0
2,3531,19026214,-29.959008,57.134378,-2363.433693,460.477339,9998,33401,-2368.123418,557.6,-1,-2367.0
3,3564,19026215,-29.726710,56.957153,-2565.191551,667.349575,9998,33401,-2620.603166,665.8,9998,-2621.0
4,3595,19026216,-29.330182,56.889742,-2668.932239,1784.921199,9998,33401,-2627.649528,1832.5,9998,-2626.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3901,3565,6903804138,28.170320,34.867470,-2709.512331,719.585314,-1,33401,-2677.673309,669.7,9998,-2682.0
3902,3583,6903804139,28.345508,34.909088,-2714.402968,701.986780,-1,33401,-2737.439074,659.8,9998,-2741.0
3903,3596,6903804140,28.535035,34.932555,-2691.854767,558.410115,-1,33401,-2679.670902,527.6,9998,-2678.0
3904,3613,6903804141,28.661340,34.965030,-2798.658885,436.248084,-1,33401,-2812.467302,408.1,9998,-2812.0
3905,3627,6903804142,28.654533,34.969773,-2764.366147,453.692136,-1,33401,-2782.652303,404.4,9998,-2794.0

In [38]:
dsa1[(dsa1['tid_flag']==-1)&(dsa1['tid_flag2']==-1)]

,index,WMO,lon,lat,grnd,uncertainty,tid_flag,SID,gebco,uncertainty2,tid_flag2,gebco2
188,691,69029832,-10.076152,-9.859370,-3841.705540,1206.720995,-1,33401,-3837.099895,1145.9,-1,-3835.0
639,1752,690175646,-29.928160,49.956425,-3118.442775,2054.654787,-1,33401,-2925.881703,1901.4,-1,-2928.0
668,105,690175853,-39.394330,51.264680,-3800.758849,1118.116131,-1,33401,-3632.478303,816.3,-1,-3632.0
843,570,690281177,-38.390850,55.069227,-2772.062800,525.704119,-1,33401,-2775.214860,181.9,-1,-2780.0
846,589,690281180,-38.382653,55.029678,-2864.962896,546.720250,-1,33401,-2839.377735,194.5,-1,-2841.0
999,443,690281956,-29.497512,53.609850,-3271.666199,1262.810187,-1,33401,-3239.004825,599.4,-1,-3239.0
1152,619,690288252,-38.722877,56.421943,-2865.597650,664.718515,-1,33401,-2941.868188,650.7,-1,-2953.0
1413,3850,690289554,-52.565117,58.582718,-3445.792807,640.350576,-1,33401,-3433.933056,623.2,-1,-3438.0
1463,1299,690297227,-30.298558,46.649435,-3467.968513,2020.248858,-1,33401,-3467.072782,1961.8,-1,-3471.0
1515,2707,690297281,-32.172565,44.686833,-3361.229983,1482.729434,-1,33401,-3310.832960,1448.9,-1,-3304.0
1521,2864,690297287,-30.981853,44.713832,-2986.982247,1552.242439,-1,33401,-3047.387598,1520.6,-1,-3048.0
1528,3041,690297294,-30.920300,44.894820,-2945.854739,1552.093153,-1,33401,-3084.818845,1509.5,-1,-3086.0
1547,2895,690297387,-37.795760,50.546710,-3747.438697,2316.434928,-1,33401,-3643.980462,2228.7,-1,-3641.0
1669,1687,690297639,-52.877080,59.322640,-3441.686181,1327.356783,-1,33401,-3443.039532,1258.8,-1,-3443.0
1733,2906,690297783,-37.204850,-51.935083,-3815.134920,1534.780918,-1,33401,-3862.766417,1386.7,-1,-3863.0
1755,734,690298317,-10.376022,-9.675355,-3600.371626,908.122402,-1,33401,-3618.949984,864.5,-1,-3620.0
2051,2232,690303259,-49.886350,55.505140,-3617.236415,395.578358,-1,33401,-3617.935163,375.6,-1,-3618.0
2150,2562,690303471,-42.739500,47.646640,-3495.939555,8189.385929,-1,33401,-3554.674252,8189.9,-1,-3555.0
2258,2211,690304028,-57.528367,58.270593,-2861.244045,3365.993230,-1,33401,-2876.263650,3242.6,-1,-2877.0
2367,2009,690304220,-58.143220,57.495940,-2817.441167,2203.538781,-1,33401,-2318.912746,2078.7,-1,-2321.0
2461,2122,690308225,-23.121732,58.363760,-2965.770543,4099.286591,-1,33401,-2949.137211,4084.5,-1,-2949.0
2480,2694,690308246,-25.360340,59.663262,-2364.900178,353.349008,-1,33401,-2308.108452,332.6,-1,-2307.0
2615,2954,690308556,-25.106810,59.607000,-2365.890367,185.941430,-1,33401,-2373.112088,155.6,-1,-2373.0
2645,1865,690308615,-36.264680,57.762190,-2910.227875,362.335947,-1,33401,-2976.291311,342.4,-1,-2973.0
3160,2123,690387125,-31.763727,52.855612,-3224.057649,1782.009739,-1,33401,-3396.185908,1764.1,-1,-3386.0
3161,2149,690387126,-31.077713,52.718560,-3436.800963,3061.214565,-1,33401,-3516.387858,2994.7,-1,-3516.0
3170,2392,690387135,-30.658240,52.829540,-3290.434628,1909.867150,-1,33401,-3359.958807,1820.4,-1,-3350.0
3171,2419,690387136,-30.589952,52.875207,-3254.311093,1661.714258,-1,33401,-3264.993166,1587.6,-1,-3255.0
3223,3833,690387188,-29.053932,53.861312,-3116.375759,404.374761,-1,33401,-3093.526119,473.9,-1,-3094.0
3375,849,3902131139,0.791907,-8.584012,-3099.328585,1373.949156,-1,33401,-3387.601954,466.6,-1,-3414.0
3376,19,6901632113,-21.791800,46.106030,-3931.110801,2296.385723,-1,33401,-3831.189618,1619.2,-1,-3849.0
3384,775,6902811103,-37.541480,54.493093,-3011.692083,348.240327,-1,33401,-3018.529507,149.5,-1,-3008.0

In [35]:
dsa1[dsa1['tid_flag']==9999]

,index,WMO,lon,lat,grnd,uncertainty,tid_flag,SID,gebco,uncertainty2,tid_flag2,gebco2
601,200,690160311,-34.070830,56.733180,-1941.822073,4076.731846,9999,33401,-968.140995,947.3,9998,-1027.0
669,111,690175856,-40.450570,51.709580,-3870.703537,3257.924877,9999,33401,-3066.746894,2414.1,9998,-3064.0
687,113,690176020,-40.196960,61.225810,-2830.272580,5553.379383,9999,33401,-1977.324747,3204.5,9998,-1981.0
807,343,690281141,-38.912397,52.038967,-3669.981518,5487.365755,9999,33401,-2827.377731,3323.2,9998,-2818.0
1366,1934,690289447,-39.041202,-49.295875,-3620.212149,10572.418710,9999,33401,-5003.632681,10020.2,9998,-4949.0
1436,2691,690297076,-34.720962,50.258892,-3538.984602,3715.931679,9999,33401,-2568.813842,3529.1,-1,-2581.0
2152,3131,690303493,-39.075420,48.632860,-3027.938100,1517.129238,9999,33401,-4040.358128,1431.1,-1,-4006.0
2267,2457,690304037,-50.313590,51.904740,-2981.109702,10768.000290,9999,33401,-1823.462179,10483.4,9998,-1838.0
2402,2664,690307159,-10.552230,35.068270,-3307.470349,282.566668,9999,33401,-4454.990241,269.5,9998,-4455.0
2433,2312,690308133,-20.941460,45.764160,-3672.083378,466.610454,9999,33401,-4581.463785,446.2,9998,-4583.0
2456,1965,690308219,-22.268000,56.148660,-3187.020760,885.505471,9999,33401,-1326.775405,848.2,9998,-1326.0
3537,3320,6902886100,-44.300090,59.507770,-2826.749032,8615.394137,9999,33401,-655.611809,7359.2,9998,-692.0
3579,3413,6902892103,-30.055890,-49.901840,-3470.836520,6549.160993,9999,33401,-4720.966423,6140.2,-1,-4721.0
3649,2968,6902975100,-20.908590,51.743110,-3180.441721,1405.634796,9999,33401,-4325.146448,1369.6,-1,-4327.0
3807,3312,6903571110,13.269480,73.537030,-2372.498593,1255.527226,9999,33401,-1544.436063,1101.5,9998,-1544.0

In [24]:
dss1 = pd.read_csv('grounding_solo_cmfile_25.csv')
dss1 = dss1.sort_values(['WMO']).reset_index()
dss1

,index,WMO,lon,lat,grnd,uncertainty,tid_flag,SID,gebco,uncertainty2,tid_flag2,gebco2
0,34,19022688,57.35527,-25.23995,-4169.856,936.1544,9998,33400,-3945.600666,1418.4,9998,-3946.0
1,1863,39021629,-34.92955,0.20592,-4537.750,1934.6200,-1,33400,-4544.946465,2681.2,9998,-4545.0
2,2484,39022046,-35.13216,-17.97665,-3457.438,1493.2450,9998,33400,-4092.618661,900.9,9998,-4093.0
3,2485,39022047,-35.19984,-17.85973,-3457.166,1601.0830,-1,33400,-4119.152231,982.4,9998,-4119.0
4,2486,39022048,-35.31861,-17.78240,-3454.442,2057.2960,9998,33400,-4148.936745,1242.5,9998,-4149.0
...,...,...,...,...,...,...,...,...,...,...,...,...
12360,12359,7900922128,148.84160,-60.99720,-4014.478,3633.7230,9998,33400,-3972.206318,2409.3,-1,-3971.0
12361,12360,7900922129,148.86980,-60.99145,-4013.216,3612.3550,9998,33400,-3983.254293,2382.5,-1,-3984.0
12362,12361,7900922130,148.78680,-61.05170,-3922.393,3682.5240,-1,33400,-3870.798894,2420.7,-1,-3869.0
12363,12362,7900922131,148.79030,-61.04733,-3925.700,3675.5460,-1,33400,-3878.374994,2418.1,-1,-3877.0
12364,12363,7900922132,148.56290,-61.03643,-3781.160,3704.7440,-1,33400,-3768.065218,2444.0,9998,-3770.0

In [36]:
dss1[dss1['tid_flag']==9999]

,index,WMO,lon,lat,grnd,uncertainty,tid_flag,SID,gebco,uncertainty2,tid_flag2,gebco2
21,7116,59057587,-171.77200,-32.28264,-1633.195,369.2291,9999,33400,-3835.368084,389.4,9998,-3827.0
22,7117,59057588,-171.75300,-32.27637,-1772.956,369.3327,9999,33400,-3991.486362,418.8,9998,-4007.0
77,37,190226815,57.64537,-24.82270,-4036.640,992.4007,9999,33400,-5117.199994,950.5,-1,-5119.0
112,75,390131018,-21.66961,-2.10078,-1459.639,2569.4000,9999,33400,-4907.345665,1284.3,9998,-4902.0
3424,6212,590252966,-158.00640,-32.62445,-4994.180,790.7032,9999,33400,-3951.654861,1006.2,9998,-3958.0
6145,11097,590668364,-165.00860,-0.21625,-5233.398,1415.3770,9999,33400,-2042.960160,2015.4,9998,-1704.0
6975,11976,590691612,175.23030,-54.63121,-1973.197,997.4413,9999,33400,-5042.703694,781.5,9998,-5042.0
6976,11977,590691613,175.17910,-54.54468,-1950.435,1284.3280,9999,33400,-5099.131534,695.0,9998,-5101.0
6977,11978,590691614,175.10490,-54.44892,-1922.861,1248.0750,9999,33400,-5118.407262,663.6,9998,-5116.0
7183,12330,790092238,140.30720,-63.13286,-2954.112,4796.3900,9999,33400,-3792.461520,2689.8,9998,-3792.0
7184,12331,790092239,140.42940,-63.20669,-2952.240,3922.2600,9999,33400,-3795.890757,2084.1,9998,-3796.0
7185,12332,790092240,140.15830,-63.29417,-2953.588,5203.0730,9999,33400,-3786.531131,2747.6,9998,-3787.0
7186,12333,790092241,139.70990,-63.31696,-2952.998,7233.4210,9999,33400,-3774.447997,3790.1,9998,-3774.0
7187,12334,790092242,139.28950,-63.20974,-2954.583,8463.1040,9999,33400,-3787.948987,4438.2,9998,-3788.0
7188,12335,790092243,139.32720,-63.03627,-2954.328,6160.1250,9999,33400,-3770.061411,3199.9,9998,-3770.0
7191,12338,790092246,140.70700,-63.26904,-2954.766,2808.8070,9999,33400,-3805.929917,1463.1,9998,-3806.0
9910,5998,5902527129,108.87230,-37.30999,-4467.526,747.3770,9999,33400,-5282.899254,741.5,9998,-5278.0
9918,6006,5902527141,107.68800,-37.00201,-4420.592,731.9055,9999,33400,-5786.486189,698.0,9998,-5787.0
10378,7185,5905758113,-172.73650,-25.52888,-1755.169,508.3688,9999,33400,-5776.973499,552.1,9998,-5780.0
10379,7186,5905758129,-172.64520,-25.37392,-1815.279,445.9821,9999,33400,-5302.951278,506.4,9998,-5303.0
10380,7187,5905758130,-172.68010,-25.37153,-1864.323,442.5791,9999,33400,-5191.143618,520.8,9998,-5187.0
10381,7188,5905758131,-172.71080,-25.37242,-1823.946,440.7978,9999,33400,-5152.070927,509.8,9998,-5152.0
10382,7189,5905758132,-172.73610,-25.37936,-1413.438,444.9537,9999,33400,-5138.820220,398.0,9998,-5130.0
10383,7190,5905758133,-172.77420,-25.38896,-1662.557,451.1002,9999,33400,-5622.188559,468.6,9998,-5618.0
10429,7236,5905758225,-170.80790,-23.47623,-4816.312,745.8664,9999,33400,-5698.787039,777.8,9998,-5700.0
10432,7239,5905758228,-171.99640,-23.65692,-4767.761,711.6818,9999,33400,-5666.355184,717.7,9998,-5668.0
11821,9949,5906360872,-136.97730,-52.57689,-1762.448,2776.2040,9999,33400,-4391.731108,3016.7,-1,-4393.0